In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.preprocessing import LabelEncoder

In [30]:
data = pd.read_csv("fraud1.csv")

In [31]:
data

Unnamed: 0  step      type      amount     nameOrig  oldbalanceOrg  \
0               0   162  CASH_OUT   183806.32   C691771226       19391.00   
1               1   137   PAYMENT      521.37   C203378011           0.00   
2               2   179   PAYMENT     3478.18  C1698571270       19853.00   
3               3   355   PAYMENT     1716.05   C913764937        5769.17   
4               4   354   CASH_IN   253129.93  C2017736577     1328499.49   
...           ...   ...       ...         ...          ...            ...   
16421       16421   743  CASH_OUT   339682.13   C786484425      339682.13   
16422       16422   743  TRANSFER  6311409.28  C1529008245     6311409.28   
16423       16423   743  CASH_OUT  6311409.28  C1162922333     6311409.28   
16424       16424   743  TRANSFER   850002.52  C1685995037      850002.52   
16425       16425   743  CASH_OUT   850002.52  C1280323807      850002.52   

       newbalanceOrig     nameDest  oldbalanceDest  newbalanceDest  \
0                0.00  C1416312719       382572.19       566378.51   
1                0.00    M42773300            0.00            0.00   
2            16374.82   M643984524            0.00            0.00   
3             4053.13  M1387429131            0.00            0.00   
4          1581629.42   C407484102      2713220.48      2460090.55   
...               ...          ...             ...             ...   
16421            0.00   C776919290            0.00       339682.13   
16422            0.00  C1881841831            0.00            0.00   
16423            0.00  C1365125890        68488.84      6379898.11   
16424            0.00  C2080388513            0.00            0.00   
16425            0.00   C873221189      6510099.11      7360101.63   

       isFlaggedFraud  isFraud  
0                   0        0  
1                   0        0  
2                   0        0  
3                   0        0  
4                   0        0  
...               ...      ...  
16421               0        1  
16422               0        1  
16423               0        1  
16424               0        1  
16425               0        1  

[16426 rows x 12 columns]

In [32]:
data["type"].unique()

array(['CASH_OUT', 'PAYMENT', 'CASH_IN', 'TRANSFER', 'DEBIT'],
      dtype=object)

In [33]:
# 0. CASH_IN, 1. CASH_OUT, 2. DEBIT, 3. PAYMENT, 4. TRANSFER

In [34]:
label_encoder = LabelEncoder()
data['type'] = label_encoder.fit_transform(data['type'])
data

Unnamed: 0  step  type      amount     nameOrig  oldbalanceOrg  \
0               0   162     1   183806.32   C691771226       19391.00   
1               1   137     3      521.37   C203378011           0.00   
2               2   179     3     3478.18  C1698571270       19853.00   
3               3   355     3     1716.05   C913764937        5769.17   
4               4   354     0   253129.93  C2017736577     1328499.49   
...           ...   ...   ...         ...          ...            ...   
16421       16421   743     1   339682.13   C786484425      339682.13   
16422       16422   743     4  6311409.28  C1529008245     6311409.28   
16423       16423   743     1  6311409.28  C1162922333     6311409.28   
16424       16424   743     4   850002.52  C1685995037      850002.52   
16425       16425   743     1   850002.52  C1280323807      850002.52   

       newbalanceOrig     nameDest  oldbalanceDest  newbalanceDest  \
0                0.00  C1416312719       382572.19       566378.51   
1                0.00    M42773300            0.00            0.00   
2            16374.82   M643984524            0.00            0.00   
3             4053.13  M1387429131            0.00            0.00   
4          1581629.42   C407484102      2713220.48      2460090.55   
...               ...          ...             ...             ...   
16421            0.00   C776919290            0.00       339682.13   
16422            0.00  C1881841831            0.00            0.00   
16423            0.00  C1365125890        68488.84      6379898.11   
16424            0.00  C2080388513            0.00            0.00   
16425            0.00   C873221189      6510099.11      7360101.63   

       isFlaggedFraud  isFraud  
0                   0        0  
1                   0        0  
2                   0        0  
3                   0        0  
4                   0        0  
...               ...      ...  
16421               0        1  
16422               0        1  
16423               0        1  
16424               0        1  
16425               0        1  

[16426 rows x 12 columns]

In [35]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16426 entries, 0 to 16425
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Unnamed: 0      16426 non-null  int64  
 1   step            16426 non-null  int64  
 2   type            16426 non-null  int32  
 3   amount          16426 non-null  float64
 4   nameOrig        16426 non-null  object 
 5   oldbalanceOrg   16426 non-null  float64
 6   newbalanceOrig  16426 non-null  float64
 7   nameDest        16426 non-null  object 
 8   oldbalanceDest  16426 non-null  float64
 9   newbalanceDest  16426 non-null  float64
 10  isFlaggedFraud  16426 non-null  int64  
 11  isFraud         16426 non-null  int64  
dtypes: float64(5), int32(1), int64(4), object(2)
memory usage: 1.4+ MB


In [36]:
data.drop(["step","nameOrig","nameDest","Unnamed: 0"],axis = 1, inplace=True)

In [37]:
data

type      amount  oldbalanceOrg  newbalanceOrig  oldbalanceDest  \
0         1   183806.32       19391.00            0.00       382572.19   
1         3      521.37           0.00            0.00            0.00   
2         3     3478.18       19853.00        16374.82            0.00   
3         3     1716.05        5769.17         4053.13            0.00   
4         0   253129.93     1328499.49      1581629.42      2713220.48   
...     ...         ...            ...             ...             ...   
16421     1   339682.13      339682.13            0.00            0.00   
16422     4  6311409.28     6311409.28            0.00            0.00   
16423     1  6311409.28     6311409.28            0.00        68488.84   
16424     4   850002.52      850002.52            0.00            0.00   
16425     1   850002.52      850002.52            0.00      6510099.11   

       newbalanceDest  isFlaggedFraud  isFraud  
0           566378.51               0        0  
1                0.00               0        0  
2                0.00               0        0  
3                0.00               0        0  
4          2460090.55               0        0  
...               ...             ...      ...  
16421       339682.13               0        1  
16422            0.00               0        1  
16423      6379898.11               0        1  
16424            0.00               0        1  
16425      7360101.63               0        1  

[16426 rows x 8 columns]

In [38]:
X = data.drop(columns=["isFraud"])  # Features
y = data["isFraud"]  # Target variable

In [39]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [40]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [41]:
X_train.shape[1]

7

In [42]:
# Building the ANN
model = Sequential([
    Dense(units=64, activation='relu', input_dim=X_train.shape[1]),
    Dense(units=32, activation='relu'),
    Dense(units=32, activation='relu'),
    Dense(units=16, activation='relu'),
    Dense(units=2, activation='softmax')  # Final layer with softmax activation
])

In [43]:
# Compiling the ANN
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

# Training the ANN
model.fit(X_train, y_train, batch_size=10000, epochs=10, validation_split=0.2)

Epoch 1/10
2/2 [==============================] - 2s 270ms/step - loss: 0.6937 - accuracy: 0.5848 - val_loss: 0.6803 - val_accuracy: 0.6948
Epoch 2/10
2/2 [==============================] - 0s 51ms/step - loss: 0.6796 - accuracy: 0.6980 - val_loss: 0.6694 - val_accuracy: 0.7173
Epoch 3/10
2/2 [==============================] - 0s 48ms/step - loss: 0.6679 - accuracy: 0.7118 - val_loss: 0.6589 - val_accuracy: 0.7485
Epoch 4/10
2/2 [==============================] - 0s 46ms/step - loss: 0.6570 - accuracy: 0.7526 - val_loss: 0.6486 - val_accuracy: 0.7534
Epoch 5/10
2/2 [==============================] - 0s 31ms/step - loss: 0.6467 - accuracy: 0.7510 - val_loss: 0.6381 - val_accuracy: 0.7580
Epoch 6/10
2/2 [==============================] - 0s 36ms/step - loss: 0.6364 - accuracy: 0.7623 - val_loss: 0.6284 - val_accuracy: 0.8052
Epoch 7/10
2/2 [==============================] - 0s 38ms/step - loss: 0.6268 - accuracy: 0.7979 - val_loss: 0.6188 - val_accuracy: 0.8048
Epoch 8/10
2/2 [==========

In [44]:
# Predicting the probabilities of each class
y_pred_prob = model.predict(X_test)

# Predicting the class with the highest probability
y_pred = np.argmax(y_pred_prob, axis=1)

# Printing the predicted probabilities and class predictions
print("Predicted Probabilities:")
print(y_pred_prob)
print("Predicted Classes:")
print(y_pred)

103/103 [==============================] - 0s 2ms/step
Predicted Probabilities:
array([[0.40640423, 0.5935958 ],
       [0.44569752, 0.55430245],
       [0.55897737, 0.44102266],
       ...,
       [0.4306974 , 0.5693026 ],
       [0.5248638 , 0.4751362 ],
       [0.5652708 , 0.4347292 ]], dtype=float32)
Predicted Classes:
array([1, 1, 0, ..., 1, 0, 0], dtype=int64)


In [46]:
from sklearn.metrics import classification_report
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

           0       0.93      0.73      0.82      2094
           1       0.66      0.91      0.76      1192

    accuracy                           0.80      3286
   macro avg       0.80      0.82      0.79      3286
weighted avg       0.83      0.80      0.80      3286



In [47]:
type(X_test)

numpy.ndarray

In [48]:
model.save("fraud.h5")

c:\Users\user\anaconda3\Lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


In [49]:
from tensorflow import *
loaded_model = keras.saving.load_model("fraud.h5")

In [50]:
pred1 = loaded_model.predict(np.array([X_test[0]]))

1/1 [==============================] - 0s 100ms/step


In [51]:
pred1[0]

array([0.40640423, 0.5935958 ], dtype=float32)